name: Build and Push app-service Image

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  IMG: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMG }}:${{ env.version }}
            ${{ env.IMG }}:${{ env.version_major }}.${{ env.version_minor }}.latest
            ${{ env.IMG }}:${{ env.version_major }}.latest
            ${{ env.IMG }}:latest

bump-version:
    runs-on: ubuntu-24.04
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Install bumpver
        run: pip install bumpver

      - name: Determine next pre-release version
        id: next_version
        run: |
          CURRENT_VERSION=${GITHUB_REF#refs/tags/v}
          NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." $2 "." $3+1 "-pre"}')
          echo "next_version=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Bump version to next pre-release
        run: bumpver update --new-version ${{ env.next_version }}

      - name: Commit and push changes
        run: |
          git add pyproject.toml
          git commit -m "Bump version to ${{ env.next_version }}"
          git push origin main
